### ISSUE TITLE
understand difference between edge_trace and node_trace

### ISSUE THREAD

**Issue by trevorspreadbury** [uchicago-dsi/climate-cabinet-campaign-finance-tracker#85]
```
    # TODO: understand difference between edge_trace and node_trace
```

https://github.com/dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker/blob/6289156899c02b94711ae953786dde51884520cf/src/utils/network.py#L165

**Comment by bhavyapan** [comment]
Each node on the graph represents the entity name, while each edge represents the attribute amount and transactions. Node traces are used to plot node entities in the visualization. Each node's position is determined by its coordinates. Edge traces are used to draw lines or curves that represent connections. They are plotted from the coordinates of one node to another.
