### ISSUE TITLE
what are the classification values?

### ISSUE THREAD

**Issue by trevorspreadbury** [uchicago-dsi/climate-cabinet-campaign-finance-tracker#87]
```
        #TODO: what are the classification values?
```

https://github.com/dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker/blob/6289156899c02b94711ae953786dde51884520cf/src/utils/network.py#L191

**Comment by bhavyapan** [comment]
Neutral classification for almost all entities in the `transactions_table.csv` and `individuals_table.csv` files under `output/cleaned` directory. "c" stands for clean and "f" for fossil-fuel.

**Comment by trevorspreadbury** [comment]
Makes sense -- these could probably use a better name or be documented somewhere
